ruby '3.1.2'
source 'https://rubygems.org'
gem 'activegraph', '~> 11.1.0.alpha.3'
gem 'anystyle'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'httpx'
gem 'neo4j-ruby-driver', '~> 4.4.0.alpha.6'
gem 'rubocop', group: 'development'
gem 'ruby-progressbar', '~> 1.11'
gem 'serrano'
