require 'require_all'

require './lib/env'
require './lib/utils'
require './lib/logger'
require './lib/datasource'
require './lib/models'
require './lib/datamining/anystyle'
require './lib/matcher'
require './lib/export/wos'